### ISSUE TITLE
Ingame swords still display in aeolus

### ISSUE THREAD

**Issue by Kalvirox** [FAForever/server#200]
The crossed swords still display between adjuton and I even though the game ended days ago. I have played other games since then and refafed several times but this has not solved the issue.

**Comment by micheljung** [comment]
This should be fixed by #201

**Comment by shalkya** [comment]
http://imgur.com/o3AKfHe
still happening

**Comment by Geosearchef** [comment]
Still happening, on both clients, everytime I join, I get a message from the server containing this game: (which ended about a week ago)
faflive://lobby.faforever.com/55538999/73910.SCFAreplay?map=equilibrium.v0007&mod=phantomx

![alreadyingame](https://cloud.githubusercontent.com/assets/5748922/21547432/506f193a-cde6-11e6-8bb1-fc795c583959.PNG)

**Comment by hugst** [comment]
Any update on this?

**Comment by shalkya** [comment]
![image](https://user-images.githubusercontent.com/11618427/28332579-a0e36cc4-6bf5-11e7-92c9-a42ef6279b4c.png)
still happening. (just a reminder)

**Comment by Askaholic** [comment]
Pretty sure this is fixed by #576
